### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by crazy4groovy** [deepsweet/foxr#20]
```
$ firefox -headless -marionette -safe-mode

$ npm start

> ff-headless@1.0.0 start C:\dev\projects\scrap\ff-headless
> node .

{ Error: connect ECONNREFUSED 127.0.0.1:2828
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 2828 }
```

FF 61.0.2
on Windows 10
Note that this command does work: `firefox -screenshot https://developer.mozilla.com`

**Comment by deepsweet** [comment]
Hi.

Please try the following code:

```js
const { Socket } = require('net')

const socket = new Socket()

socket
  .once('data', (data) => console.log(data.toString()))
  .connect(2828, 'localhost')
```

If it doesn't return `50:{"applicationType":"gecko","marionetteProtocol":3}` then I'm afraid that it's related to Windows antivirus/firewall or whatever is blocking port `2828`.

**Comment by deepsweet** [comment]
@crazy4groovy any luck with this?

**Comment by deepsweet** [comment]
Please feel free to ping me here again so we can re-open the issue.

**Comment by crazy4groovy** [comment]
```
D:\dev\projects\scrap\firefox-headless>node test
50:{"applicationType":"gecko","marionetteProtocol":3}
```

**Comment by crazy4groovy** [comment]
Oooo! It seems that every run will kill the browser, which makes sense now with `await browser.close()`
I don't think there's a problem. Thanks for your response :+1:
