### ISSUE TITLE
implement page.goBack()

### ISSUE THREAD

**Issue by deepsweet** [deepsweet/foxr#35]
https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagegobackoptions

**Comment by tharun208** [comment]
Hi, Can I work on this issue

**Comment by deepsweet** [comment]
Would be great! Feel free to ask anything, Python implementation is [here](https://searchfox.org/mozilla-central/source/testing/marionette/client/marionette_driver/marionette.py#1621)

**Comment by tharun208** [comment]
Hi,, if 
    Can you tell me how to start with the development for the project.It would be good ,if you would give a clean instruction of how to setup the project and also ways to run it.
