### ISSUE TITLE
implement foxr.launch()

### ISSUE THREAD

**Issue by deepsweet** [deepsweet/foxr#5]
https://github.com/GoogleChrome/puppeteer/blob/v1.6.2/docs/api.md#puppeteerlaunchoptions

* download Firefox
  * which version and how to control that?
  * multiplatform
* unpack it
  * to where?
* run it as child process with necessary [args](https://github.com/deepsweet/firefox-headless-remote/blob/master/entrypoint.sh) and [profile](https://github.com/deepsweet/firefox-headless-remote/blob/master/profile/prefs.js)
* kill that process on `browser.close()`

**Comment by MusiKid** [comment]
I have investigated and there is some problems:
- there is no zip archive for Windows (except for nightly: https://support.mozilla.org/fr/questions/784553), 
- there is no way to get them (easily).
I don't know if macOS dmg's will do the trick but Linux versions seems to work.

**Comment by deepsweet** [comment]
Hi.

macOS `.dmg` is just a renamed `.zip` archive, should just work.

Regarding Windows – I found this:

* https://www.firefox-usb.com/
* https://portableapps.com/apps/internet/firefox_portable

Not sure how much we can trust these sources though.

**Comment by deepsweet** [comment]
Also https://github.com/freaktechnik/get-firefox

**Comment by MusiKid** [comment]
Sorry, hi !
I'm not sure about firefox-usb but I know that Firefox Portable is open-source.
And get-firefox seems to be more a CLI app than an usable API.

**Comment by MusiKid** [comment]
Ok so I tried to build the `launch()` function with get-firefox but it was more easy to proceed using taskcluster-client. 
I finally succeed to download Firefox but when I launched it, I discovered that it needs to create a new profile to make it separated from other firefox processes and preferences.

**Comment by deepsweet** [comment]
Yeah, I've already done this in my dockerized headless Firefox project, see [args](https://github.com/deepsweet/firefox-headless-remote/blob/master/entrypoint.sh) and [profile](https://github.com/deepsweet/firefox-headless-remote/blob/master/profile/prefs.js). We could place the profile in the same folder to where we downloaded Firefox.

**Comment by MusiKid** [comment]
I didn't looked at it before, it would have helped me a lot !
The problem that I was facing is the `-profile` argument for which I gave a file instead of a folder.
But now I will test it.

**Comment by deepsweet** [comment]
I'd check where Puppeteer stores Chromium, it feels like it's in their module folder inside of `node_modules/`.

Also, I'd like to initially implement this as a separate package to not make the same mistake as Puppeteer – see [puppeteer vs puppeteer-core](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteer-vs-puppeteer-core). Something like you have to install `foxr` and `download-firefox-blah-blah` to avoid `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD` env var hackaround and then `launch()` will do the rest. We can transform this repo into a monorepo with `@foxr` namespace, I've it registered already. What do you think?

Thanks for your investigation!

**Comment by deepsweet** [comment]
>will have to test the presence of download-firefox and use an exported function

That's the weak part of my idea :) My personal usage of Foxr/Puppeteer is limited to an external dockerized solution, so that `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD` felt like a hack until they introduced `puppeteer-core` thing. There is no need to download entire browser by default, I believe that it should be an opt-in.

How to wire it together is a good question.

`launch()` has an `executablePath` option, so maybe "downloader" can export some property with the file path of downloaded browser.

**Comment by foolip** [comment]
@jgraham probably knows how to download Firefox automatically, this is done in web-platform-tests, although in Python, here:
https://github.com/web-platform-tests/wpt/blob/59bed3508ceae6bd16e31971c3d0448d13a5113b/tools/wpt/browser.py#L132

**Comment by MusiKid** [comment]
Thanks for the help! But I already built a module that can do this. The problem is how to "modularize" the function.

**Comment by deepsweet** [comment]
If you choose a path to download Firefox in deterministic way, i.e. it doesn't have random parts and it gives the same result every time, you can export it and pass to Foxr:

```js
foxr.launch({
  executablePath: firefoxDownloader.getPath()
})
```

**Comment by MusiKid** [comment]
The path could change with the OS (maybe not if it's relative) ?

**Comment by deepsweet** [comment]
It's fine as long as "firefox-downloader" module will use the same path as it returns with `getPath()`.

**Comment by MusiKid** [comment]
I pushed my changes on the launch branch of my fork

**Comment by deepsweet** [comment]
Looks good! I'm a bit off this project for the last few days, but will come back really soon.

**Comment by deepsweet** [comment]
Alright.

I'm going to implement `launch()` as an abstract downloads-free method, and then we'll think about a monorepo under `@foxr` NPM scope.

**Comment by MusiKid** [comment]
Ok

**Comment by MusiKid** [comment]
I created an example module to download Firefox.

**Comment by MusiKid** [comment]
The module is more complete now. macOS support needs to be tested however.

**Comment by deepsweet** [comment]
Nice. Shouldn't `download()` be `await`'ed in readme?

**Comment by MusiKid** [comment]
Effectively !

**Comment by MusiKid** [comment]
So where should Firefox be extracted ?

**Comment by deepsweet** [comment]
I'm not quite sure. What's your current solution?

**Comment by MusiKid** [comment]
I don't know

**Comment by MusiKid** [comment]
Maybe just let the user define it ?
