### ISSUE TITLE
Get innerText of element

### ISSUE THREAD

**Issue by wallace7souza** [deepsweet/foxr#50]
HI! 
I'm have noob question, How can I get the innertext of a tag using the current foxr api?
I had tried some  code with no success.
Thanks!

**Comment by deepsweet** [comment]
Hi.

With what is currently implemented you can use `await page.$eval('h1', (el) => el.innerText)` where `h1` is element selector.

**Comment by deepsweet** [comment]
Or:

```js
const el = await page.$('.selector')
const text = await page.evaluate((el) => el.innerText, el)
```
