### ISSUE TITLE
Can't see browser with `launch`

### ISSUE THREAD

**Issue by victorhqc** [deepsweet/foxr#54]
Not sure if this is a problem or I just don't know how to use `foxr`. I can launch a browser and take a screenshot as in the example, but even if I disable the headless mode I can't see the browser.

```js
foxr.launch({
    headless: false,
    args: ['-marionette', '-safe-mode', '-no-remote', '-profile', '/tmp/firefox_test-test_123'],
    executablePath: '/my-path/firefox',
  });
```

This is not something that blocks my workflow, I can just open another window and check using screenshots, but feels a bit too troublesome 🤔 am I missing something?

**Comment by victorhqc** [comment]
Update: it was my own fault, not sure what happened, maybe I was wrapping something in a try/catch block, or it was an promise I wasn't handling correctly. Closing this issue now.

**Comment by deepsweet** [comment]
glad to help :)
